### ISSUE TITLE
Dynamics 365: An unsecured or incorrectly secured fault was received from the other party

### ISSUE THREAD

**Issue by PlunketNZ** [DawidPotgieter/Dynamics-CRM-Binary-Storage-Options#1]
I was receiving a "An unsecured or incorrectly secured fault was received from the other party" on authenticating against AzureAD with "Migrate" against D365 / AzureAD.

This was solved by updating the Microsoft.Xrm.Sdk and Microsoft.Crm.Sdk.Proxy dlls to 9.0.0.0. Nuget solution:
![xmr sdk](https://user-images.githubusercontent.com/19719356/32761684-98e1bd0c-c959-11e7-9cc3-049832f0166a.PNG)

**Comment by DawidPotgieter** [comment]
Thanks for the feedback ghost.
