### ISSUE TITLE
Question: Attachment Searchability

### ISSUE THREAD

**Issue by steveplatz** [DawidPotgieter/Dynamics-CRM-Binary-Storage-Options#11]
With relevance search enabled, attachments stored in CRM are searchable. Is the same true for attachments stored in Azure Blob or Azure File Storage?

**Comment by DawidPotgieter** [comment]
Hi Steve,

I don't have any direct experience with this.  However, having done a quick scan of the architecture posted here : https://technet.microsoft.com/en-us/library/mt723654.aspx, I can't see why it wouldn't work.
This seems to use a push mechanism where the relevance search pushes all your data via service bus to some blob storage (not the same one as where the documents are stored, this is relevant only to the search indexing).  So I'd imagine the plugins would all execute as normal.

As always, would be great if you could test and provide some feedback though.

Cheers.

**Comment by steveplatz** [comment]
@DawidPotgieter I installed the Microsoft Attachment Management plugin in our environment to test integration with Azure Blob storage.  I assume it likely works very similar to what you've developed.  I can confirm that with that add-in, attachments stored in Azure Blob storage are **not** searchable. (i.e. no full-text indexing seems to be performed on blob attachments)

![image](https://user-images.githubusercontent.com/15626/47041918-fd7d3000-d157-11e8-86a5-018028d41fcc.png)

Image above:
1. Attachment stored in CRM
    * "This is a test file upload" - text file contents
2. Attachment copied to Azure Blob Storage
3. Attachment copied to Azure Blob Storage; Note has text

**Comment by DawidPotgieter** [comment]
Thanks a lot for that info.

I don't have any insight into how the Microsoft plugin works, but I notice that theirs requires a custom ui in the form of a web resource.
This leads me to believe that they are not using exactly the same method, but I can't be sure.

In regards to the Relevance search :

It depends on whether it circumvents the crm api (which invokes plugins) or goes straight to the database like Azure SQL Data Sync seems to do.  It looks from the architecture documents that they may have plugged in via the API, but it's always impossible to find any real technical details in these cases, so testing is your only option I'm afraid.

I will actually be looking at this issue in the near(ish) future, as I'm planning on using it as well, so will keep everyone posted here.

**Comment by DawidPotgieter** [comment]
I'm going to close this by answering that it's unlikely that Relevance Search will work with this plugin.  From what I can gather, Microsoft circumvents the supported plugin interface for this.
