### ISSUE TITLE
how to get AES 256 encryption key and salt from Azure Storage account

### ISSUE THREAD

**Issue by san-86** [DawidPotgieter/Dynamics-CRM-Binary-Storage-Options#2]
Hello, I'm trying to set the solution up in and CRM 2015 environment,
I have created the storage account in Azure and activated encryption, but I can't find the AES265 encryption key anywhere in azure and I can't find any info about it when I google, what am I missing ?

**Comment by DawidPotgieter** [comment]
Hi Soeren,

The AES key is what you provide if you want client side (crm server) encryption, it is independent of azure. So if you set the encryption provider as AES, you need to give it a “password”. Same with the salt, just a string you make up that makes the encryption better.

Hope that helps.

________________________________

**Comment by san-86** [comment]
Thank you that makes sense
