### ISSUE TITLE
Access Question

### ISSUE THREAD

**Issue by KeithMattMurphy** [DawidPotgieter/Dynamics-CRM-Binary-Storage-Options#20]
Hi Dawid
This looks like a fantastic solution.
Maybe a silly question but I'm unsure how the security works with this?
Will only the CRM owners of the Note/Email be able to view the attachment once moved to blob storage or can anyone inside / outside the organisation see it?

thanks a million
Keith

**Comment by DawidPotgieter** [comment]
Hi there Keith,

When ou set up your blob storage, you would set that to ‘private’. This means that only someone/systems with your storage key will have access to the files.

You then provide that key to CRM in configuration, which only CRM administrators have rights to.

The plugins do not actually move notes or emails, only the binary part of the attachments.

Thus, in reality, the access is controlled by CRM, and you configure those on a role by role basis. Think of it as the security staying the same as it was, except you’re using different underlying storage.

Hope that answers your question.

________________________________

**Comment by KeithMattMurphy** [comment]
Hi David

That's great - thanks very much.
Looking forward to testing it out

Regards
Keith
