### ISSUE TITLE
Migration 4.1 does not work with CRM online

### ISSUE THREAD

**Issue by san-86** [DawidPotgieter/Dynamics-CRM-Binary-Storage-Options#8]
After Microsoft have updated the default TLS version to 1.2 the current version of Migrate 4.1 won't work, have you experienced this before ? 

I have tried to download the source code and I can see that the nuget packages used is old, so they will need to be updated I think

**Comment by DawidPotgieter** [comment]
Hi there.

Yes, for Dynamics 365, you have to update the nuget packages. I left it as is because it is easier to upgrade than downgrade.

Cheers

________________________________

**Comment by san-86** [comment]
After Update Of nuget packages and Rebuilding the Migrate solution works again
