### ISSUE TITLE
Problem with IfdSelected variable in Migrate Solution

### ISSUE THREAD

**Issue by san-86** [DawidPotgieter/Dynamics-CRM-Binary-Storage-Options#9]
I have tried to run a migration against a Online 8.2 instance, at first the migrate program found nothing to move, I then tried to debug the application and found that it chose a wrong OrganizationServiceProxy,

the code that creates the problem is : 
`private bool IfdSelected
		{
			get
			{
				bool value = false;
				if (rdoIFDAuth.InvokeRequired)
				{
					rdoIFDAuth.BeginInvoke(new MethodInvoker(delegate { value = rdoIFDAuth.Checked; }));
				}
				else
				{
					value = rdoIFDAuth.Checked;
				}
				return value;
			}
		}`
and the place where it's used
` if (IfdSelected)
            {
                localProxy = new OrganizationServiceProxy(serviceManagement, authCredentials.SecurityTokenResponse);
            }
            else
            {
                localProxy = new OrganizationServiceProxy(serviceManagement, authCredentials.ClientCredentials);
            }`

When the IfdSelected is used the BeginInvoke is called as it should but the value returned is still false, so the local Proxy will use the wrong Authentication method and fail several places in the migrate program.

I have fixed it by setting it to use the SecurityTokenResponse Auth everytime but a better way could probably be found.

**Comment by DawidPotgieter** [comment]
I have tried to replicate this, but I can't seem to find the issue you're experiencing.  

Are you saying that if you tick the "IFD" tickbox, that rdoIFDAuth.Checked returns false?  Seems very odd, as that's just making sure that the code is being called on the correct thread.

What .net framework are you running (and which version of the CRM sdk)?  That's the only thing I can think of to still try to replicate the issue.

Cheers.

**Comment by DawidPotgieter** [comment]
Hi there,

Is this still an issue, or can I mark it as resolved?

Thanks.

**Comment by san-86** [comment]
Hi ,

You can close it

Thank you.
________________________________
Fra: Dawid Potgieter <notifications@github.com>
Sendt: 7. juni 2018 22:33
Til: DawidPotgieter/Dynamics-CRM-Binary-Storage-Options
Cc: Soeren Andersen; Author
Emne: Re: [DawidPotgieter/Dynamics-CRM-Binary-Storage-Options] Problem with IfdSelected variable in Migrate Solution (#9)


Hi there,

Is this still an issue, or can I mark it as resolved?

Thanks.

**Comment by DawidPotgieter** [comment]
Thanks.

Would you mind providing the answer to the problem, just in case someone else runs into something similar?

Cheers.

**Comment by san-86** [comment]
I changed the code to check un check the button Ifdselected and then it worked, it was very odd
